export const SUPPORTED_FILE_TYPES = [
  'TXT',
  'UTF-16 text',
  'Suffixless text/config',
  'CSV',
  'TSV',
  'JSON',
  'JSONL/NDJSON',
  'Markdown',
  'LOG',
  'XML',
  'HTML/HTM',
  'RTF',
  'PDF text layer',
  'DOCX',
  'XLSX',
  'PPTX',
  'DOC/XLS/PPT legacy Office text',
  'ODT',
  'ODS',
  'ODP',
  'EML email',
  'ZIP archives',
  'PDF image OCR',
  'PNG/JPG image OCR',
  'TIFF/BMP/WEBP image OCR',
  'VTT/SRT video transcripts',
  'MP4/MOV/M4V/MKV/WEBM/AVI video frame OCR',
  'Google Docs export',
  'Google Sheets export',
  'Google Slides export',
]

export const SUPPORTED_FILE_TYPES_DESCRIPTION = 'Core scanners read these formats during scan execution.'
export const SUPPORTED_FILE_TYPES_NOTE = 'OCR-backed PDF, image, and video-frame scans require host-local OCR tools, FFmpeg, and installed language packs. Legacy binary Office scans require host-local LibreOffice. Deterministic scans do not use AI by default.'
