import type { LanguagePreferenceCode } from './languages'

export const translations: Record<LanguagePreferenceCode, Record<string, string>> = {
  en: {},
  bg: { Dashboard: 'Табло', Sources: 'Източници', Findings: 'Констатации', 'Audit trail': 'Одитна следа', Evaluation: 'Оценка', Governance: 'Управление', Theme: 'Тема', Language: 'Език', Feedback: 'Обратна връзка', Help: 'Помощ', Docs: 'Документи', 'Log Out': 'Изход', 'Prototype plan': 'Прототипен план', 'Platform Status': 'Статус на платформата', Precision: 'Прецизност', Recall: 'Обхват', 'F1 score': 'F1 резултат', Reproducibility: 'Възпроизводимост' },
  hr: { Dashboard: 'Nadzorna ploča', Sources: 'Izvori', Findings: 'Nalazi', 'Audit trail': 'Revizijski trag', Evaluation: 'Evaluacija', Governance: 'Upravljanje', Theme: 'Tema', Language: 'Jezik', Feedback: 'Povratne informacije', Help: 'Pomoć', Docs: 'Dokumenti', 'Log Out': 'Odjava', 'Prototype plan': 'Prototipni plan', 'Platform Status': 'Status platforme', Precision: 'Preciznost', Recall: 'Odziv', 'F1 score': 'F1 rezultat', Reproducibility: 'Ponovljivost' },
  cs: { Dashboard: 'Řídicí panel', Sources: 'Zdroje', Findings: 'Nálezy', 'Audit trail': 'Auditní stopa', Evaluation: 'Vyhodnocení', Governance: 'Správa', Theme: 'Motiv', Language: 'Jazyk', Feedback: 'Zpětná vazba', Help: 'Nápověda', Docs: 'Dokumentace', 'Log Out': 'Odhlásit', 'Prototype plan': 'Plán prototypu', 'Platform Status': 'Stav platformy', Precision: 'Přesnost', Recall: 'Záchyt', 'F1 score': 'F1 skóre', Reproducibility: 'Reprodukovatelnost' },
  da: { Dashboard: 'Dashboard', Sources: 'Kilder', Findings: 'Fund', 'Audit trail': 'Revisionsspor', Evaluation: 'Evaluering', Governance: 'Styring', Theme: 'Tema', Language: 'Sprog', Feedback: 'Feedback', Help: 'Hjælp', Docs: 'Dokumenter', 'Log Out': 'Log ud', 'Prototype plan': 'Prototypeplan', 'Platform Status': 'Platformstatus', Precision: 'Præcision', Recall: 'Genfinding', 'F1 score': 'F1-score', Reproducibility: 'Reproducerbarhed' },
  nl: { Dashboard: 'Dashboard', Sources: 'Bronnen', Findings: 'Bevindingen', 'Audit trail': 'Auditspoor', Evaluation: 'Evaluatie', Governance: 'Governance', Theme: 'Thema', Language: 'Taal', Feedback: 'Feedback', Help: 'Hulp', Docs: 'Documentatie', 'Log Out': 'Uitloggen', 'Prototype plan': 'Prototypeplan', 'Platform Status': 'Platformstatus', Precision: 'Precisie', Recall: 'Recall', 'F1 score': 'F1-score', Reproducibility: 'Reproduceerbaarheid' },
  et: { Dashboard: 'Töölaud', Sources: 'Allikad', Findings: 'Leidud', 'Audit trail': 'Auditijälg', Evaluation: 'Hindamine', Governance: 'Juhtimine', Theme: 'Teema', Language: 'Keel', Feedback: 'Tagasiside', Help: 'Abi', Docs: 'Dokumendid', 'Log Out': 'Logi välja', 'Prototype plan': 'Prototüübi plaan', 'Platform Status': 'Platvormi olek', Precision: 'Täpsus', Recall: 'Tuvastatavus', 'F1 score': 'F1 skoor', Reproducibility: 'Korratavus' },
  fi: { Dashboard: 'Koontinäyttö', Sources: 'Lähteet', Findings: 'Löydökset', 'Audit trail': 'Auditointiloki', Evaluation: 'Arviointi', Governance: 'Hallinta', Theme: 'Teema', Language: 'Kieli', Feedback: 'Palaute', Help: 'Ohje', Docs: 'Dokumentit', 'Log Out': 'Kirjaudu ulos', 'Prototype plan': 'Prototyyppisuunnitelma', 'Platform Status': 'Alustan tila', Precision: 'Tarkkuus', Recall: 'Kattavuus', 'F1 score': 'F1-tulos', Reproducibility: 'Toistettavuus' },
  fr: { Dashboard: 'Tableau de bord', Sources: 'Sources', Findings: 'Constats', 'Audit trail': 'Journal d’audit', Evaluation: 'Évaluation', Governance: 'Gouvernance', Theme: 'Thème', Language: 'Langue', Feedback: 'Retour', Help: 'Aide', Docs: 'Docs', 'Log Out': 'Déconnexion', 'Prototype plan': 'Plan du prototype', 'Platform Status': 'État de la plateforme', Precision: 'Précision', Recall: 'Rappel', 'F1 score': 'Score F1', Reproducibility: 'Reproductibilité' },
  de: { Dashboard: 'Dashboard', Sources: 'Quellen', Findings: 'Befunde', 'Audit trail': 'Audit-Protokoll', Evaluation: 'Auswertung', Governance: 'Governance', Theme: 'Design', Language: 'Sprache', Feedback: 'Feedback', Help: 'Hilfe', Docs: 'Dokumente', 'Log Out': 'Abmelden', 'Prototype plan': 'Prototyp-Plan', 'Platform Status': 'Plattformstatus', Precision: 'Präzision', Recall: 'Trefferquote', 'F1 score': 'F1-Wert', Reproducibility: 'Reproduzierbarkeit' },
  el: { Dashboard: 'Πίνακας ελέγχου', Sources: 'Πηγές', Findings: 'Ευρήματα', 'Audit trail': 'Ίχνος ελέγχου', Evaluation: 'Αξιολόγηση', Governance: 'Διακυβέρνηση', Theme: 'Θέμα', Language: 'Γλώσσα', Feedback: 'Σχόλια', Help: 'Βοήθεια', Docs: 'Έγγραφα', 'Log Out': 'Αποσύνδεση', 'Prototype plan': 'Σχέδιο πρωτοτύπου', 'Platform Status': 'Κατάσταση πλατφόρμας', Precision: 'Ακρίβεια', Recall: 'Ανάκληση', 'F1 score': 'Βαθμός F1', Reproducibility: 'Αναπαραγωγιμότητα' },
  hu: { Dashboard: 'Irányítópult', Sources: 'Források', Findings: 'Találatok', 'Audit trail': 'Auditnapló', Evaluation: 'Értékelés', Governance: 'Irányítás', Theme: 'Téma', Language: 'Nyelv', Feedback: 'Visszajelzés', Help: 'Súgó', Docs: 'Dokumentumok', 'Log Out': 'Kijelentkezés', 'Prototype plan': 'Prototípus terv', 'Platform Status': 'Platform állapota', Precision: 'Pontosság', Recall: 'Felidézés', 'F1 score': 'F1 pontszám', Reproducibility: 'Reprodukálhatóság' },
  ga: { Dashboard: 'Painéal', Sources: 'Foinsí', Findings: 'Torthaí', 'Audit trail': 'Rian iniúchta', Evaluation: 'Measúnú', Governance: 'Rialachas', Theme: 'Téama', Language: 'Teanga', Feedback: 'Aiseolas', Help: 'Cabhair', Docs: 'Doiciméid', 'Log Out': 'Logáil amach', 'Prototype plan': 'Plean fréamhshamhla', 'Platform Status': 'Stádas ardáin', Precision: 'Beachtas', Recall: 'Aisghairm', 'F1 score': 'Scór F1', Reproducibility: 'In-atáirgtheacht' },
  it: { Dashboard: 'Dashboard', Sources: 'Origini', Findings: 'Rilievi', 'Audit trail': 'Registro audit', Evaluation: 'Valutazione', Governance: 'Governance', Theme: 'Tema', Language: 'Lingua', Feedback: 'Feedback', Help: 'Aiuto', Docs: 'Documenti', 'Log Out': 'Disconnetti', 'Prototype plan': 'Piano prototipo', 'Platform Status': 'Stato piattaforma', Precision: 'Precisione', Recall: 'Richiamo', 'F1 score': 'Punteggio F1', Reproducibility: 'Riproducibilità' },
  lv: { Dashboard: 'Informācijas panelis', Sources: 'Avoti', Findings: 'Atradumi', 'Audit trail': 'Audita pēdas', Evaluation: 'Novērtējums', Governance: 'Pārvaldība', Theme: 'Motīvs', Language: 'Valoda', Feedback: 'Atsauksmes', Help: 'Palīdzība', Docs: 'Dokumenti', 'Log Out': 'Izrakstīties', 'Prototype plan': 'Prototipa plāns', 'Platform Status': 'Platformas statuss', Precision: 'Precizitāte', Recall: 'Atsaukums', 'F1 score': 'F1 rezultāts', Reproducibility: 'Atkārtojamība' },
  lt: { Dashboard: 'Skydelis', Sources: 'Šaltiniai', Findings: 'Radimai', 'Audit trail': 'Audito seka', Evaluation: 'Vertinimas', Governance: 'Valdymas', Theme: 'Tema', Language: 'Kalba', Feedback: 'Atsiliepimai', Help: 'Pagalba', Docs: 'Dokumentai', 'Log Out': 'Atsijungti', 'Prototype plan': 'Prototipo planas', 'Platform Status': 'Platformos būsena', Precision: 'Tikslumas', Recall: 'Atgaminimas', 'F1 score': 'F1 balas', Reproducibility: 'Atkuriamumas' },
  mt: { Dashboard: 'Dashboard', Sources: 'Sorsi', Findings: 'Sejbiet', 'Audit trail': 'Traċċa tal-awditjar', Evaluation: 'Evalwazzjoni', Governance: 'Governanza', Theme: 'Tema', Language: 'Lingwa', Feedback: 'Feedback', Help: 'Għajnuna', Docs: 'Dokumenti', 'Log Out': 'Oħroġ', 'Prototype plan': 'Pjan tal-prototip', 'Platform Status': 'Status tal-pjattaforma', Precision: 'Preċiżjoni', Recall: 'Recall', 'F1 score': 'Punteġġ F1', Reproducibility: 'Riproduċibbiltà' },
  pl: { Dashboard: 'Panel', Sources: 'Źródła', Findings: 'Ustalenia', 'Audit trail': 'Ścieżka audytu', Evaluation: 'Ewaluacja', Governance: 'Zarządzanie', Theme: 'Motyw', Language: 'Język', Feedback: 'Opinie', Help: 'Pomoc', Docs: 'Dokumenty', 'Log Out': 'Wyloguj', 'Prototype plan': 'Plan prototypu', 'Platform Status': 'Status platformy', Precision: 'Precyzja', Recall: 'Czułość', 'F1 score': 'Wynik F1', Reproducibility: 'Powtarzalność' },
  pt: { Dashboard: 'Painel', Sources: 'Fontes', Findings: 'Achados', 'Audit trail': 'Trilho de auditoria', Evaluation: 'Avaliação', Governance: 'Governação', Theme: 'Tema', Language: 'Idioma', Feedback: 'Feedback', Help: 'Ajuda', Docs: 'Documentos', 'Log Out': 'Terminar sessão', 'Prototype plan': 'Plano do protótipo', 'Platform Status': 'Estado da plataforma', Precision: 'Precisão', Recall: 'Revocação', 'F1 score': 'Pontuação F1', Reproducibility: 'Reprodutibilidade' },
  ro: { Dashboard: 'Tablou de bord', Sources: 'Surse', Findings: 'Constatări', 'Audit trail': 'Jurnal de audit', Evaluation: 'Evaluare', Governance: 'Guvernanță', Theme: 'Temă', Language: 'Limbă', Feedback: 'Feedback', Help: 'Ajutor', Docs: 'Documente', 'Log Out': 'Deconectare', 'Prototype plan': 'Plan prototip', 'Platform Status': 'Stare platformă', Precision: 'Precizie', Recall: 'Rechemare', 'F1 score': 'Scor F1', Reproducibility: 'Reproductibilitate' },
  sk: { Dashboard: 'Panel', Sources: 'Zdroje', Findings: 'Nálezy', 'Audit trail': 'Auditná stopa', Evaluation: 'Vyhodnotenie', Governance: 'Riadenie', Theme: 'Téma', Language: 'Jazyk', Feedback: 'Spätná väzba', Help: 'Pomoc', Docs: 'Dokumenty', 'Log Out': 'Odhlásiť', 'Prototype plan': 'Plán prototypu', 'Platform Status': 'Stav platformy', Precision: 'Presnosť', Recall: 'Záchyt', 'F1 score': 'F1 skóre', Reproducibility: 'Reprodukovateľnosť' },
  sl: { Dashboard: 'Nadzorna plošča', Sources: 'Viri', Findings: 'Ugotovitve', 'Audit trail': 'Revizijska sled', Evaluation: 'Vrednotenje', Governance: 'Upravljanje', Theme: 'Tema', Language: 'Jezik', Feedback: 'Povratne informacije', Help: 'Pomoč', Docs: 'Dokumenti', 'Log Out': 'Odjava', 'Prototype plan': 'Načrt prototipa', 'Platform Status': 'Stanje platforme', Precision: 'Natančnost', Recall: 'Priklic', 'F1 score': 'Ocena F1', Reproducibility: 'Ponovljivost' },
  es: { Dashboard: 'Panel', Sources: 'Fuentes', Findings: 'Hallazgos', 'Audit trail': 'Registro de auditoría', Evaluation: 'Evaluación', Governance: 'Gobernanza', Theme: 'Tema', Language: 'Idioma', Feedback: 'Comentarios', Help: 'Ayuda', Docs: 'Documentos', 'Log Out': 'Cerrar sesión', 'Prototype plan': 'Plan del prototipo', 'Platform Status': 'Estado de la plataforma', Precision: 'Precisión', Recall: 'Exhaustividad', 'F1 score': 'Puntuación F1', Reproducibility: 'Reproducibilidad' },
  sv: { Dashboard: 'Instrumentpanel', Sources: 'Källor', Findings: 'Fynd', 'Audit trail': 'Granskningsspår', Evaluation: 'Utvärdering', Governance: 'Styrning', Theme: 'Tema', Language: 'Språk', Feedback: 'Feedback', Help: 'Hjälp', Docs: 'Dokument', 'Log Out': 'Logga ut', 'Prototype plan': 'Prototypplan', 'Platform Status': 'Plattformsstatus', Precision: 'Precision', Recall: 'Återkallning', 'F1 score': 'F1-poäng', Reproducibility: 'Reproducerbarhet' },
}

export const supplementalTranslations: Partial<Record<LanguagePreferenceCode, Record<string, string>>> = {
  fr: {
    'Account settings': 'Paramètres du compte', 'Home Page': 'Page d’accueil', Changelog: 'Journal des changements', 'Server connected': 'Serveur connecté', 'Server disconnected': 'Serveur déconnecté', 'Checking server': 'Vérification du serveur', 'Privacy workspace': 'Espace de travail confidentialité', 'Theme options': 'Options de thème', 'Language preference': 'Préférence de langue', 'Close account menu': 'Fermer le menu du compte', 'Account menu': 'Menu du compte', 'Open account menu': 'Ouvrir le menu du compte', 'Expand sidebar': 'Développer la barre latérale', 'Collapse sidebar': 'Réduire la barre latérale', 'Close navigation': 'Fermer la navigation', 'Quick search': 'Recherche rapide', 'Quick search...': 'Recherche rapide...', 'Primary navigation': 'Navigation principale', Notifications: 'Notifications', 'Dismiss notification': 'Ignorer la notification',
    'Measurable discovery': 'Découverte mesurable', 'Evaluation metrics': 'Métriques d’évaluation', 'Risk progress': 'Progression du risque', 'False negatives': 'Faux négatifs', Throughput: 'Débit', 'Paid service cost': 'Coût du service payant', 'Resource intensity': 'Intensité des ressources', 'Peak memory': 'Pic mémoire', 'CPU time': 'Temps CPU', 'Paid services': 'Services payants', Used: 'Utilisés', 'Not used': 'Non utilisés', 'Cost per 1k files': 'Coût par 1 000 fichiers', 'Reproducibility record': 'Enregistrement de reproductibilité', 'Evaluation run': 'Exécution d’évaluation', 'Scanner version': 'Version du scanner', 'Dataset hash': 'Hash du jeu de données', 'Rules hash': 'Hash des règles', 'Admin metrics hash': 'Hash des métriques admin', 'Evaluation hash': 'Hash d’évaluation', 'Config hash': 'Hash de configuration', 'Not available': 'Non disponible', 'Quality basis': 'Base qualité', 'Evaluated files': 'Fichiers évalués', 'Actual positives': 'Positifs réels', 'Predicted positives': 'Positifs prédits', 'True positives': 'Vrais positifs', 'True negatives': 'Vrais négatifs', 'Review throughput': 'Débit de revue', day: 'jour', 'Safety boundaries': 'Limites de sécurité', 'Raw content exposed': 'Contenu brut exposé', 'Legal conclusion provided': 'Conclusion juridique fournie', 'Deletion executed': 'Suppression exécutée', 'Model calls': 'Appels de modèle', Yes: 'Oui', No: 'Non', 'Scenario quality': 'Qualité par scénario', 'Unknown context': 'Contexte inconnu', seconds: 'secondes', '{{count}} high-risk remaining': '{{count}} risques élevés restants', '{{count}} false positive': '{{count}} faux positif', '{{rate}} files/s': '{{rate}} fichiers/s', '{{percent}}% complete': '{{percent}} % terminé',
  },
  de: {
    'Account settings': 'Kontoeinstellungen', 'Home Page': 'Startseite', Changelog: 'Änderungsprotokoll', 'Server connected': 'Server verbunden', 'Server disconnected': 'Server getrennt', 'Checking server': 'Server wird geprüft', 'Privacy workspace': 'Datenschutz-Arbeitsbereich', 'Language preference': 'Spracheinstellung', 'Quick search': 'Schnellsuche', 'Quick search...': 'Schnellsuche...', 'Measurable discovery': 'Messbare Erkennung', 'Risk progress': 'Risikofortschritt', 'False negatives': 'Falsch negative', Throughput: 'Durchsatz', 'Paid service cost': 'Kosten bezahlter Dienste', 'Resource intensity': 'Ressourcenintensität', 'Peak memory': 'Spitzen-Speicher', 'CPU time': 'CPU-Zeit', 'Paid services': 'Bezahlte Dienste', Used: 'Verwendet', 'Not used': 'Nicht verwendet', 'Cost per 1k files': 'Kosten pro 1.000 Dateien', 'Reproducibility record': 'Reproduzierbarkeitsnachweis', 'Evaluation run': 'Evaluierungslauf', 'Scanner version': 'Scanner-Version', 'Dataset hash': 'Datensatz-Hash', 'Rules hash': 'Regel-Hash', 'Admin metrics hash': 'Admin-Metriken-Hash', 'Evaluation hash': 'Evaluierungs-Hash', 'Config hash': 'Konfigurations-Hash', 'Not available': 'Nicht verfügbar', 'Quality basis': 'Qualitätsbasis', 'Evaluated files': 'Bewertete Dateien', 'Actual positives': 'Tatsächliche Positive', 'Predicted positives': 'Vorhergesagte Positive', 'True positives': 'Richtig positive', 'True negatives': 'Richtig negative', 'Review throughput': 'Prüf-Durchsatz', day: 'Tag', 'Safety boundaries': 'Sicherheitsgrenzen', 'Raw content exposed': 'Rohinhalt offengelegt', 'Legal conclusion provided': 'Rechtliche Schlussfolgerung bereitgestellt', 'Deletion executed': 'Löschung ausgeführt', 'Model calls': 'Modellaufrufe', Yes: 'Ja', No: 'Nein', 'Scenario quality': 'Szenarioqualität', 'Unknown context': 'Unbekannter Kontext', seconds: 'Sekunden', '{{count}} high-risk remaining': '{{count}} hohe Risiken verbleibend', '{{count}} false positive': '{{count}} falsch positiv', '{{rate}} files/s': '{{rate}} Dateien/s', '{{percent}}% complete': '{{percent}} % abgeschlossen',
  },
  es: {
    'Account settings': 'Configuración de cuenta', 'Home Page': 'Página de inicio', Changelog: 'Registro de cambios', 'Server connected': 'Servidor conectado', 'Server disconnected': 'Servidor desconectado', 'Checking server': 'Comprobando servidor', 'Privacy workspace': 'Espacio de privacidad', 'Language preference': 'Preferencia de idioma', 'Quick search': 'Búsqueda rápida', 'Quick search...': 'Búsqueda rápida...', 'Measurable discovery': 'Descubrimiento medible', 'Risk progress': 'Progreso del riesgo', 'False negatives': 'Falsos negativos', Throughput: 'Rendimiento', 'Paid service cost': 'Coste del servicio de pago', 'Resource intensity': 'Intensidad de recursos', 'Peak memory': 'Memoria máxima', 'CPU time': 'Tiempo de CPU', 'Paid services': 'Servicios de pago', Used: 'Usado', 'Not used': 'No usado', 'Cost per 1k files': 'Coste por 1.000 archivos', 'Reproducibility record': 'Registro de reproducibilidad', 'Evaluation run': 'Ejecución de evaluación', 'Scanner version': 'Versión del escáner', 'Dataset hash': 'Hash del conjunto de datos', 'Rules hash': 'Hash de reglas', 'Admin metrics hash': 'Hash de métricas de administración', 'Evaluation hash': 'Hash de evaluación', 'Config hash': 'Hash de configuración', 'Not available': 'No disponible', 'Quality basis': 'Base de calidad', 'Evaluated files': 'Archivos evaluados', 'Actual positives': 'Positivos reales', 'Predicted positives': 'Positivos predichos', 'True positives': 'Verdaderos positivos', 'True negatives': 'Verdaderos negativos', 'Review throughput': 'Rendimiento de revisión', day: 'día', 'Safety boundaries': 'Límites de seguridad', 'Raw content exposed': 'Contenido bruto expuesto', 'Legal conclusion provided': 'Conclusión legal proporcionada', 'Deletion executed': 'Eliminación ejecutada', 'Model calls': 'Llamadas al modelo', Yes: 'Sí', No: 'No', 'Scenario quality': 'Calidad por escenario', 'Unknown context': 'Contexto desconocido', seconds: 'segundos', '{{count}} high-risk remaining': '{{count}} de alto riesgo restantes', '{{count}} false positive': '{{count}} falso positivo', '{{rate}} files/s': '{{rate}} archivos/s', '{{percent}}% complete': '{{percent}} % completado',
  },
}

export const selectedTemplates: Record<LanguagePreferenceCode, string> = {
  en: '{{language}} selected',
  bg: 'Избран език: {{language}}',
  hr: 'Odabrano: {{language}}',
  cs: 'Vybráno: {{language}}',
  da: '{{language}} valgt',
  nl: '{{language}} geselecteerd',
  et: '{{language}} valitud',
  fi: '{{language}} valittu',
  fr: '{{language}} sélectionné',
  de: '{{language}} ausgewählt',
  el: 'Επιλέχθηκε: {{language}}',
  hu: '{{language}} kiválasztva',
  ga: '{{language}} roghnaithe',
  it: '{{language}} selezionato',
  lv: 'Atlasīts: {{language}}',
  lt: 'Pasirinkta: {{language}}',
  mt: '{{language}} magħżul',
  pl: 'Wybrano: {{language}}',
  pt: '{{language}} selecionado',
  ro: '{{language}} selectată',
  sk: 'Vybraté: {{language}}',
  sl: 'Izbrano: {{language}}',
  es: '{{language}} seleccionado',
  sv: '{{language}} valt',
}
